#!/bin/bash

# https://stackoverflow.com/questions/28811811/how-to-use-gdb-in-16-bit-mode
# https://tomiylab.com/2021/09/gdb-mikanos/

qemu-system-i386 -rtc base=localtime -drive file=boot.img,format=raw -boot order=c
